#include<stdio.h>
#include<unistd.h>
#include<stdlib.h>
#include<string.h>
int main()
{
    FILE *filePointer ;
    system("cls");
    system("Color 90");
    filePointer = fopen("Resume.txt", "w") ;
    char line[100]
        = "=========================================================================";
    char name[100], address[100],email[100],phone[100],linkedin[100],career[1000],position[100],nationality[100],references[100];
    char exam[100],year[100],institution[100],training[100],courses[100],special[100],dob[100],date[100],name1[100];
    char projects[100],grades[100],exp[100],comp[100],resp[100],language[100],activities[100],hobbies[100];
    printf("\nEnter your Name : ");
    scanf("%[^\n]%*c", name);
    printf("\nEnter your Address : ");
    scanf("%[^\n]%*c", address);
    printf("\nEnter your Email : ");
    scanf("%[^\n]%*c", email);
    printf("\nEnter your Phone NUmber : ");
    scanf("%[^\n]%*c", phone);
    printf("\nEnter your linkedin I'd : ");
    scanf("%[^\n]%*c", linkedin);
    printf("\nEnter your Career Objective : ");
    scanf("%[^\n]%*c",career);
    printf("\nEnter your Position Sought : ");
    scanf("%[^\n]%*c",position);
    printf("\nEnter your Career Objective: ");
    scanf("%[^\n]%*c",career);
    printf("\nEnter your Name of the Exam : ");
    scanf("%[^\n]%*c",exam);
    printf("\nEnter your Year of passing : ");
    scanf("%[^\n]%*c",year);
    printf("\nEnter your %% of marks/grades : ");
    scanf("%[^\n]%*c",institution);
    printf("\nEnter your Institution : ");
    scanf("%[^\n]%*c",grades);
    printf("\nEnter your Name of the comp : ");
    scanf("%[^\n]%*c",comp);
    printf("\nEnter your Job Responsibility : ");
    scanf("%[^\n]%*c",resp);
    printf("\nEnter your Projects Undertaken : ");
    scanf("%[^\n]%*c",projects);
    printf("\nEnter your Internship/Training : ");
    scanf("%[^\n]%*c",training);
    printf("\nEnter your Online Training/Courses : ");
    scanf("%[^\n]%*c",courses);
    printf("\nEnter your Language Known : ");
    scanf("%[^\n]%*c",language);
    printf("\nEnter your Co-Curricular Activities : ");
    scanf("%[^\n]%*c",activities);
    printf("\nEnter your Hobbies : ");
    scanf("%[^\n]%*c",hobbies);
    printf("\nEnter your Special Achievements : ");
    scanf("%[^\n]%*c",special);
    printf("\nEnter your Mother or Father Name : ");
    scanf("%[^\n]%*c",name1);
    printf("\nEnter your Date of Birth : ");
    scanf("%[^\n]%*c",dob);
    printf("\nEnter your Nationality : ");
    scanf("%[^\n]%*c",nationality);
    printf("\nEnter your References : ");
    scanf("%[^\n]%*c",references);
    printf("\nEnter Date : ");
    scanf("%[^\n]%*c",date);
    system("cls");
    int ch;
    printf("\t\t List Of Choices Available\n");
    printf("Resume 1st Format\n");
    printf("Resume 2nd Format\n");
    printf("Resume 3rd Format\n");
    printf("Enter Your Choice:");
    scanf("%d",&ch);
    switch (ch)
    {
        case 1:
            fputs("\n                                                Name         : ", filePointer);
            fputs(name, filePointer) ;
            fputs("\n                                                Address      : ", filePointer);
            fputs(address, filePointer) ;
            fputs("\n                                                Email I'd    : ", filePointer);
            fputs(email, filePointer) ;
            fputs("\n                                                Phone Number : ", filePointer);
            fputs(phone, filePointer) ;
            fputs("\n                                                LInkedin I'd : ", filePointer);
            fputs(linkedin, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n                        ", filePointer);
            fputs(line, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n\nCareer Objective         : ", filePointer);
            fputs(career, filePointer) ;
            fputs("\nPosition Spught          : ", filePointer);
            fputs(position, filePointer);
            fputs("\n\n\nEducational Qualifications : ", filePointer);
            fputs("\n\nName of the Exam         : ", filePointer);
            fputs(exam, filePointer);
            fputs("\nYear of passing          : ", filePointer);
            fputs(year, filePointer);
            fputs("\nInstitution              : ", filePointer);
            fputs(institution, filePointer);
            fputs("\n% of marks/grades        : ",filePointer );
            fputs(grades, filePointer);
            fputs("\n\n\nProfessional experience : ",filePointer );
            fputs("\n\nName of the comp         : ",filePointer );
            fputs(comp, filePointer);
            fputs("\nJob Responsibility       : ",filePointer );
            fputs(resp, filePointer);
            fputs("\nProjects Undertaken      : ",filePointer );
            fputs(projects, filePointer);
            fputs("\nInternship/Training      : ",filePointer );
            fputs(training, filePointer);
            fputs("\nOnline Training/Courses  : ",filePointer );
            fputs(courses, filePointer);
            fputs("\nLanguage Known           : ",filePointer );
            fputs(language, filePointer);
            fputs("\nCo-Curricular Activities : ",filePointer );
            fputs(activities, filePointer);
            fputs("\nHobbies                  : ",filePointer );
            fputs(hobbies, filePointer);
            fputs("\nSpecial Achievements     : ",filePointer );
            fputs(special, filePointer);
            fputs("\n\n\nPersonal Details : ",filePointer );
            fputs("\n\nMother or Father Name    : ",filePointer );
            fputs(name1, filePointer);
            fputs("\nDate Of Birth            : ",filePointer );
            fputs(dob, filePointer);
            fputs("\nNationality              : ",filePointer );
            fputs(nationality, filePointer);
            fputs("\nAddress                  : ",filePointer );
            fputs(address, filePointer);
            fputs("\nReferences               : ",filePointer );
            fputs(references, filePointer);
            fputs("\n\n\nI do hereby confirm that the information provided is true.",filePointer );
            fputs("\n ",filePointer );
            fputs(name, filePointer);
            fputs("\n ",filePointer );
            fputs(date, filePointer);
            system("Color 0F");
            system("cls");
            printf("\nResume file has been written ");
            break;
        case 2:
            fputs("\nName         : ", filePointer);
            fputs(name, filePointer) ;
            fputs("\nAddress      : ", filePointer);
            fputs(address, filePointer) ;
            fputs("\nEmail I'd    : ", filePointer);
            fputs(email, filePointer) ;
            fputs("\nPhone Number : ", filePointer);
            fputs(phone, filePointer) ;
            fputs("\nLInkedin I'd : ", filePointer);
            fputs(linkedin, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n", filePointer);
            fputs(line, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n\nCareer Objective         : ", filePointer);
            fputs(career, filePointer) ;
            fputs("\nPosition Spught          : ", filePointer);
            fputs(position, filePointer);
            fputs("\n\n\nEducational Qualifications : ", filePointer);
            fputs("\n\nName of the Exam         : ", filePointer);
            fputs(exam, filePointer);
            fputs("\nYear of passing          : ", filePointer);
            fputs(year, filePointer);
            fputs("\nInstitution              : ", filePointer);
            fputs(institution, filePointer);
            fputs("\n% of marks/grades        : ",filePointer );
            fputs(grades, filePointer);
            fputs("\n\n\nProfessional experience : ",filePointer );
            fputs("\n\nName of the comp         : ",filePointer );
            fputs(comp, filePointer);
            fputs("\nJob Responsibility       : ",filePointer );
            fputs(resp, filePointer);
            fputs("\nProjects Undertaken      : ",filePointer );
            fputs(projects, filePointer);
            fputs("\nInternship/Training      : ",filePointer );
            fputs(training, filePointer);
            fputs("\nOnline Training/Courses  : ",filePointer );
            fputs(courses, filePointer);
            fputs("\nLanguage Known           : ",filePointer );
            fputs(language, filePointer);
            fputs("\nCo-Curricular Activities : ",filePointer );
            fputs(activities, filePointer);
            fputs("\nHobbies                  : ",filePointer );
            fputs(hobbies, filePointer);
            fputs("\nSpecial Achievements     : ",filePointer );
            fputs(special, filePointer);
            fputs("\n\n\nPersonal Details : ",filePointer );
            fputs("\n\nMother or Father Name    : ",filePointer );
            fputs(name1, filePointer);
            fputs("\nDate Of Birth            : ",filePointer );
            fputs(dob, filePointer);
            fputs("\nNationality              : ",filePointer );
            fputs(nationality, filePointer);
            fputs("\nAddress                  : ",filePointer );
            fputs(address, filePointer);
            fputs("\nReferences               : ",filePointer );
            fputs(references, filePointer);
            fputs("\n\n\nI do hereby confirm that the information provided is true.",filePointer );
            fputs("\n ",filePointer );
            fputs(name, filePointer);
            fputs("\n ",filePointer );
            fputs(date, filePointer);
            system("Color 0F");
            system("cls");
            printf("\nResume file has been written ");
            break;
        case 3:
            fputs("\n                                                Name         : ", filePointer);
            fputs(name, filePointer) ;
            fputs("\n                                                Address      : ", filePointer);
            fputs(address, filePointer) ;
            fputs("\n                                                Email I'd    : ", filePointer);
            fputs(email, filePointer) ;
            fputs("\n                                                Phone Number : ", filePointer);
            fputs(phone, filePointer) ;
            fputs("\n                                                LInkedin I'd : ", filePointer);
            fputs(linkedin, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n                        ", filePointer);
            fputs(line, filePointer) ;
            fputs("\n", filePointer) ;
            fputs("\n\n                                               Career Objective         : ", filePointer);
            fputs(career, filePointer) ;
            fputs("\n                                               Position Spught          : ", filePointer);
            fputs(position, filePointer);
            fputs("\n\n\n                                           Educational Qualifications : ", filePointer);
            fputs("\n\n                                               Name of the Exam         : ", filePointer);
            fputs(exam, filePointer);
            fputs("\n                                               Year of passing          : ", filePointer);
            fputs(year, filePointer);
            fputs("\n                                               Institution              : ", filePointer);
            fputs(institution, filePointer);
            fputs("\n                                               % of marks/grades        : ",filePointer );
            fputs(grades, filePointer);
            fputs("\n\n\n                                           Professional experience : ",filePointer );
            fputs("\n\n                                               Name of the comp         : ",filePointer );
            fputs(comp, filePointer);
            fputs("\n                                               Job Responsibility       : ",filePointer );
            fputs(resp, filePointer);
            fputs("\n                                               Projects Undertaken      : ",filePointer );
            fputs(projects, filePointer);
            fputs("\n                                               Internship/Training      : ",filePointer );
            fputs(training, filePointer);
            fputs("\n                                               Online Training/Courses  : ",filePointer );
            fputs(courses, filePointer);
            fputs("\n                                               Language Known           : ",filePointer );
            fputs(language, filePointer);
            fputs("\n                                               Co-Curricular Activities : ",filePointer );
            fputs(activities, filePointer);
            fputs("\n                                               Hobbies                  : ",filePointer );
            fputs(hobbies, filePointer);
            fputs("\n                                               Special Achievements     : ",filePointer );
            fputs(special, filePointer);
            fputs("\n\n\n                                           Personal Details : ",filePointer );
            fputs("\n\n                                               Mother or Father Name    : ",filePointer );
            fputs(name1, filePointer);
            fputs("\n                                               Date Of Birth            : ",filePointer );
            fputs(dob, filePointer);
            fputs("\n                                               Nationality              : ",filePointer );
            fputs(nationality, filePointer);
            fputs("\n                                               Address                  : ",filePointer );
            fputs(address, filePointer);
            fputs("\n                                               References               : ",filePointer );
            fputs(references, filePointer);
            fputs("\n\n\n                                           I do hereby confirm that the information provided is true.",filePointer );
            fputs("\n                                              ",filePointer );
            fputs(name, filePointer);
            fputs("\n                                              ",filePointer );
            fputs(date, filePointer);
            system("Color 0F");
            system("cls");
            printf("\nResume file has been written ");
            break;    
    }
    fclose(filePointer);
    return 0;
}